### ISSUE TITLE
Swipe back gesture not working

### ISSUE THREAD

**Issue by tmaihoff** [benPesso/flutter_cupertino_will_pop_scope#11]
Hi there, 
I want to use this package to achieve the snapping-back effect with the swipe back gesture on iOS devices. However when I set `shouldSetCallback` to `true`, the swipe back gesture is completely disabled. 

I'm using `CupertinoThemeData` and `CupertinoApp` which does not support the `pageTransitionsTheme` property. Is that maybe connected?

**Comment by benPesso** [comment]
@tmaihoff The snap-back animation is performed by the custom `CupertinoPageRoute`, as noted in the package docs. What you might try is wrapping the `CupertinoApp` with a `Theme()` and set the `pageTransitionsTheme` there.
Otherwise, you can switch back to a `MaterialApp` and use a [package like this one](https://pub.dev/packages/flutter_platform_widgets) to automatically use Cupertino widgets when needed.

**Comment by tmaihoff** [comment]
So the package does not work with `CupertinoApp` at all, correct?

I tried wrapping my `PlatformApp.router` (from flutter_platform_widgets) inside a `MaterialApp` but that gives me problems with showing modal bottom sheets. 

![image](https://user-images.githubusercontent.com/44509310/171453291-7215674a-8050-4acf-b416-c7aa394bf9fb.png)

**Comment by benPesso** [comment]
I haven't used `flutter_package_widgets` before, so I wouldn't know how that works, but you might be able to use its widgets with whatever XyzApp you want. Otherwise, my solution of wrapping the app with a `Theme` should work.
