### ISSUE TITLE
Can you expose the CupertinoPageRoute so that we can use it?

### ISSUE THREAD

**Issue by rmargolinross** [benPesso/flutter_cupertino_will_pop_scope#6]
I am using auto route and have a custom route builder that I want to use your CupertinoPageRoute on so that I can handle will pop scope correctly with it.

**Comment by rmargolinross** [comment]
Never mind, I realize now this is not needed

**Comment by rmargolinross** [comment]
I lied actually. This is. still needed in my instance.

**Comment by benPesso** [comment]
Did you mean your own `PageTransition`, or a page route? Because the `CupertinoPageRoute` on its own will not help you. You'll need something like the `ConditionalWillPopScope` widget (which my package provides). This widget alone should let you do anything you want. I just created the `CupertinoWillPopScopePageTransionsBuilder` as an extra, to provide some UI indication that the navigation gesture was cancelled. It is not needed for scope popping to work.

You can check the sample app to see how this transition is used:
```dart
    pageTransitionsTheme: PageTransitionsTheme(
      builders: {
        TargetPlatform.android: ZoomPageTransitionsBuilder(),
        TargetPlatform.iOS: CupertinoWillPopScopePageTransionsBuilder(),
      },
    ),
```

**Comment by rmargolinross** [comment]
I mean the Page Route. I am using auto_route with a custom route builder, and on ios I am injecting the CupertinoPageRoute. I then use the `ConditionalWillPopScope` on my page, and when it is true, I do not get the animation when swiping back as I believe I should. I think this is because I am manually injecting the CupertinoPageRoute which is then ignoring the injected 'TransitionsBuilders' unless I am understanding things incorrectly.

**Comment by benPesso** [comment]
Right, so if you use the `CupertinoWillPopScopePageTransionsBuilder` transition, it'll automatically load the the modified version of `CupertinoPageRoute` that has the animation.

You should be able to wrap `MaterialApp.router()` with a `Theme` that would set the `pageTransitionsTheme`, and everything should work for you. (Or if you already have a theme above it in the context tree, just add the `pageTransitionsTheme` to it.)

**Comment by benPesso** [comment]
Resolving and closing as I assume everything is good now.
